apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-second
  namespace: simple-api
spec:
  selector:
    matchLabels:
      app: simple-second
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-second
    spec:
      containers:
      - name: simple-second
        image: fxzoa/datadog-apm-simple-second
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DD_AGENT_HOST 
          valueFrom: 
            fieldRef: 
              fieldPath: status.hostIP 
        - name: TZ
          value: Asia/Tokyo
        - name: SPRING_PROFILES_ACTIVE
          value: "local"
        volumeMounts:
          - name: app-logs
            mountPath: /app/log/
      volumes:
        - name: app-logs
          hostPath:
            path: /var/log/app/cdx-auth-api/
            type: DirectoryOrCreate
