apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-service
spec:
  selector:
    matchLabels:
      app: second-service
  replicas: 1
  template:
    metadata:
      labels:
        app: second-service
    spec:
      containers:
      - name: second-service
        image: fxzoa/datadog-apm-second-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DD_AGENT_HOST 
          valueFrom: 
            fieldRef: 
              fieldPath: status.hostIP 
        - name: TZ
          value: Asia/Tokyo
        - name: SPRING_PROFILES_ACTIVE
          value: "local"
        volumeMounts:
          - name: app-logs
            mountPath: /app/log/
      volumes:
        - name: app-logs
          hostPath:
            path: /var/log/app/second-service/
            type: DirectoryOrCreate
