apiVersion: v1
kind: Service
metadata:
  name: second-service
  labels:
    app: second-service
spec:
  type: NodePort
  selector:
    app: second-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8080
