apiVersion: v1
kind: Service
metadata:
  name: first-service
  labels:
    app: first-service
spec:
  type: NodePort
  selector:
    app: first-service
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
